// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`TaskTree render 1`] = `
"  ✖ Task1
  → Error: Something bad happened
      at tasks.reverse.every (/home/kein/projects/tasktree/test/tasktree.test.ts:30:36)
      at Array.every (<anonymous>)
      at Object.it (/home/kein/projects/tasktree/test/tasktree.test.ts:18:40)
      at Object.asyncJestTest (/home/kein/projects/tasktree/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
      at resolve (/home/kein/projects/tasktree/node_modules/jest-jasmine2/build/queueRunner.js:43:12)
      at new Promise (<anonymous>)
      at mapper (/home/kein/projects/tasktree/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
      at promise.then (/home/kein/projects/tasktree/node_modules/jest-jasmine2/build/queueRunner.js:73:41)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  ⚠ Warn 2
  ℹ Log 2
  ▶ ✔ Task2
    ⚠ Warn 1
    ℹ Log 1
    ▶ ↓ Task3 [skip]
      ⚠ Warn 0
      ℹ Log 0"
`;

exports[`TaskTree render 2`] = `
"  ✖ Task1
  → Error: Something bad happened
      at tasks.reverse.every (/home/kein/projects/tasktree/test/tasktree.test.ts:30:36)
      at Array.every (<anonymous>)
      at Object.it (/home/kein/projects/tasktree/test/tasktree.test.ts:18:40)
      at Object.asyncJestTest (/home/kein/projects/tasktree/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
      at resolve (/home/kein/projects/tasktree/node_modules/jest-jasmine2/build/queueRunner.js:43:12)
      at new Promise (<anonymous>)
      at mapper (/home/kein/projects/tasktree/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
      at promise.then (/home/kein/projects/tasktree/node_modules/jest-jasmine2/build/queueRunner.js:73:41)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  ⚠ Warn 2
  ℹ Log 2
  ▶ ✔ Task2
    ⚠ Warn 1
    ℹ Log 1
    ▶ ↓ Task3 [skip]
      ⚠ Warn 0
      ℹ Log 0"
`;

exports[`TaskTree render 3`] = `""`;
